### ISSUE TITLE
Hardware installation requirements?

### ISSUE THREAD

**Issue by nagyrobi** [mathoudebine/homeassistant-timebox-mini#3]
Can you please add to the docs a small description on how to set this up on the hardware level? What kind of bluetooth adapters work, what system is recommended and how to set up multiple divooms at once?

Currently I run HA in a virtual machine, a hassio vmdk image.

**Comment by mathoudebine** [comment]
Hi, I updated the Readme with Limitations and Requirements, please check here : https://github.com/mathoudebine/homeassistant-timebox-mini/tree/feature/add-requirements#readme

For your bluetooth adapter to work, it has to be supported by Bluez library. You can check this with the command `hcitool dev`.
If you run in a VM, you have to connect your adapter to the VM (check Readme for that)

Unfortunately, this component cannot be used to control more than one Divoom device, because the controlled device need to stay connected to your adapter to display custom content.

**Comment by nagyrobi** [comment]
I see. The other problem I have is that the server running HA is too far away from the timeboxes. But I have ESP32s at those locations. Would be nice to have the ESP32s talk to the divooms instead of HA directly...

**Comment by mathoudebine** [comment]
Yes, it would make the Timebox a Wi-Fi device! I think it is possible but it can take some time to implement the Divoom communication protocol for ESP32
FYI to manage ESP32/ESP8266 easily from HomeAssistant, you may have a look et ESPHome

**Comment by nagyrobi** [comment]
I already have ESPHome happily running.
